image: python:3
lint:
 stage: build
 script:
 - pip3 install yapf 
 - yapf --recursive --diff --style google .
 only:
 -  pushes


test:
 stage: test 
 dependencies: 
 - lint
 script:
 - pip3 install -r requirements.txt
 - pytest . -v
 only:
 - pushes


prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 only:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - --quiet --project $PROJECT_ID