image: python:3
lint:
 stage: build
 script:
 - pip3 install yapf 
 - yapf --recursive --diff --style google .
 only:
 -  pushes


test:
 stage: build 
 dependencies: 
 - lint
 script:
 - pip3 install -r requirements.txt
 - pytest .
 only:
 - pushes